server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangchao210807/microservicecloud-config
          username: wangchao210807
          password: 2612999pgf