spring:
  profiles:
    active:
    - dev

---
server:
  port:9001
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev

---

server:
  port:9002
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test