spring:
  profiles:
    active:
    - dev

---
server:
  port:9001
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

---

server:
  port:9002
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka